<template>
  <div><select v-model="selected" @change="pokemonChanged()"><!-- <input type="text" v-model="search"></input> -->
    <option v-for="pokemon in pokemonList" v-bind:value="pokemon">{{pokemon.name}}</option>
  </select>
</div>
</template>

<script>
export default {
  props:['childNumber'],
  data () {
    return {
      // note: changing this line won't causes changes
      // with hot-reload because the reloaded component
      // preserves its current state and we are modifying
      // its initial state.
      search:"",
      selected:{name:'Pokemon'},
      pokemonList: [
        {name:'Pokemon'},
        { name: 'Abomasnow', type1: 'Grass', type2: 'Ice' },
        { name: 'Abra', type1: 'Psychic' },
        { name: 'Absol', type1: 'Dark' },
        { name: 'Accelgor', type1: 'Bug' },
        { name: 'Aegislash', type1: 'Steel', type2: 'Ghost' },
        { name: 'Aerodactyl', type1: 'Rock', type2: 'Flying' },
        { name: 'Aggron', type1: 'Steel', type2: 'Rock' },
        { name: 'Aipom', type1: 'Normal' },
        { name: 'Alakazam', type1: 'Psychic' },
        { name: 'Alomomola', type1: 'Water' },
        { name: 'Altaria', type1: 'Dragon', type2: 'Flying' },
        { name: 'Amaura', type1: 'Rock', type2: 'Ice' },
        { name: 'Ambipom', type1: 'Normal' },
        { name: 'Amoonguss', type1: 'Grass', type2: 'Poison' },
        { name: 'Ampharos', type1: 'Electric' },
        { name: 'Anorith', type1: 'Rock', type2: 'Bug' },
        { name: 'Arbok', type1: 'Poison' },
        { name: 'Arcanine', type1: 'Fire' },
        { name: 'Arceus', type1: 'Normal' },
        { name: 'Archen', type1: 'Rock', type2: 'Flying' },
        { name: 'Archeops', type1: 'Rock', type2: 'Flying' },
        { name: 'Ariados', type1: 'Bug', type2: 'Poison' },
        { name: 'Armaldo', type1: 'Rock', type2: 'Bug' },
        { name: 'Aromatisse', type1: 'Fairy' },
        { name: 'Aron', type1: 'Steel', type2: 'Rock' },
        { name: 'Articuno', type1: 'Ice', type2: 'Flying' },
        { name: 'Audino', type1: 'Normal' },
        { name: 'Aurorus', type1: 'Rock', type2: 'Ice' },
        { name: 'Avalugg', type1: 'Ice' },
        { name: 'Axew', type1: 'Dragon' },
        { name: 'Azelf', type1: 'Psychic' },
        { name: 'Azumarill', type1: 'Water', type2: 'Fairy' },
        { name: 'Azurill', type1: 'Normal', type2: 'Fairy' },
        { name: 'Bagon', type1: 'Dragon' },
        { name: 'Baltoy', type1: 'Ground', type2: 'Psychic' },
        { name: 'Banette', type1: 'Ghost' },
        { name: 'Barbaracle', type1: 'Rock', type2: 'Water' },
        { name: 'Barboach', type1: 'Water', type2: 'Ground' },
        { name: 'Basculin', type1: 'Water' },
        { name: 'Basculin', type1: 'Water' },
        { name: 'Bastiodon', type1: 'Rock', type2: 'Steel' },
        { name: 'Bayleef', type1: 'Grass' },
        { name: 'Beartic', type1: 'Ice' },
        { name: 'Beautifly', type1: 'Bug', type2: 'Flying' },
        { name: 'Beedrill', type1: 'Bug', type2: 'Poison' },
        { name: 'Beheeyem', type1: 'Psychic' },
        { name: 'Beldum', type1: 'Steel', type2: 'Psychic' },
        { name: 'Bellossom', type1: 'Grass' },
        { name: 'Bellsprout', type1: 'Grass', type2: 'Poison' },
        { name: 'Bergmite', type1: 'Ice' },
        { name: 'Bibarel', type1: 'Normal', type2: 'Water' },
        { name: 'Bidoof', type1: 'Normal' },
        { name: 'Binacle', type1: 'Rock', type2: 'Water' },
        { name: 'Bisharp', type1: 'Dark', type2: 'Steel' },
        { name: 'Blastoise', type1: 'Water' },
        { name: 'Blaziken', type1: 'Fire', type2: 'Fighting' },
        { name: 'Blissey', type1: 'Normal' },
        { name: 'Blitzle', type1: 'Electric' },
        { name: 'Boldore', type1: 'Rock' },
        { name: 'Bonsly', type1: 'Rock' },
        { name: 'Bouffalant', type1: 'Normal' },
        { name: 'Braixen', type1: 'Fire' },
        { name: 'Braviary', type1: 'Normal', type2: 'Flying' },
        { name: 'Breloom', type1: 'Grass', type2: 'Fighting' },
        { name: 'Bronzong', type1: 'Steel', type2: 'Psychic' },
        { name: 'Bronzor', type1: 'Steel', type2: 'Psychic' },
        { name: 'Budew', type1: 'Grass', type2: 'Poison' },
        { name: 'Buizel', type1: 'Water' },
        { name: 'Bulbasaur', type1: 'Grass', type2: 'Poison' },
        { name: 'Buneary', type1: 'Normal' },
        { name: 'Bunnelby', type1: 'Normal' },
        { name: 'Burmy', type1: 'Bug' },
        { name: 'Burmy', type1: 'Bug' },
        { name: 'Burmy', type1: 'Bug' },
        { name: 'Butterfree', type1: 'Bug', type2: 'Flying' },
        { name: 'Cacnea', type1: 'Grass' },
        { name: 'Cacturne', type1: 'Grass', type2: 'Dark' },
        { name: 'Camerupt', type1: 'Fire', type2: 'Ground' },
        { name: 'Carbink', type1: 'Rock', type2: 'Fairy' },
        { name: 'Carnivine', type1: 'Grass' },
        { name: 'Carracosta', type1: 'Water', type2: 'Rock' },
        { name: 'Carvanha', type1: 'Water', type2: 'Dark' },
        { name: 'Cascoon', type1: 'Bug' },
        { name: 'Castform', type1: 'Fire' },
        { name: 'Castform', type1: 'Normal' },
        { name: 'Castform', type1: 'Ice' },
        { name: 'Castform', type1: 'Water' },
        { name: 'Caterpie', type1: 'Bug' },
        { name: 'Celebi', type1: 'Psychic', type2: 'Grass' },
        { name: 'Chandelure', type1: 'Ghost', type2: 'Fire' },
        { name: 'Chansey', type1: 'Normal' },
        { name: 'Charizard', type1: 'Fire', type2: 'Flying' },
        { name: 'Charmander', type1: 'Fire' },
        { name: 'Charmeleon', type1: 'Fire' },
        { name: 'Chatot', type1: 'Normal', type2: 'Flying' },
        { name: 'Cherrim', type1: 'Grass' },
        { name: 'Cherubi', type1: 'Grass' },
        { name: 'Chesnaught', type1: 'Grass', type2: 'Fighting' },
        { name: 'Chespin', type1: 'Grass' },
        { name: 'Chikorita', type1: 'Grass' },
        { name: 'Chimchar', type1: 'Fire' },
        { name: 'Chimecho', type1: 'Psychic' },
        { name: 'Chinchou', type1: 'Water', type2: 'Electric' },
        { name: 'Chingling', type1: 'Psychic' },
        { name: 'Cinccino', type1: 'Normal' },
        { name: 'Clamperl', type1: 'Water' },
        { name: 'Clauncher', type1: 'Water' },
        { name: 'Clawitzer', type1: 'Water' },
        { name: 'Claydol', type1: 'Ground', type2: 'Psychic' },
        { name: 'Clefable', type1: 'Fairy' },
        { name: 'Clefairy', type1: 'Fairy' },
        { name: 'Cleffa', type1: 'Fairy' },
        { name: 'Cloyster', type1: 'Water', type2: 'Ice' },
        { name: 'Cobalion', type1: 'Steel', type2: 'Fighting' },
        { name: 'Cofagrigus', type1: 'Ghost' },
        { name: 'Combee', type1: 'Bug', type2: 'Flying' },
        { name: 'Combusken', type1: 'Fire', type2: 'Fighting' },
        { name: 'Conkeldurr', type1: 'Fighting' },
        { name: 'Corphish', type1: 'Water' },
        { name: 'Corsola', type1: 'Water', type2: 'Rock' },
        { name: 'Cottonee', type1: 'Grass', type2: 'Fairy' },
        { name: 'Cradily', type1: 'Rock', type2: 'Grass' },
        { name: 'Cranidos', type1: 'Rock' },
        { name: 'Crawdaunt', type1: 'Water', type2: 'Dark' },
        { name: 'Cresselia', type1: 'Psychic' },
        { name: 'Croagunk', type1: 'Poison', type2: 'Fighting' },
        { name: 'Crobat', type1: 'Poison', type2: 'Flying' },
        { name: 'Croconaw', type1: 'Water' },
        { name: 'Crustle', type1: 'Bug', type2: 'Rock' },
        { name: 'Cryogonal', type1: 'Ice' },
        { name: 'Cubchoo', type1: 'Ice' },
        { name: 'Cubone', type1: 'Ground' },
        { name: 'Cyndaquil', type1: 'Fire' },
        { name: 'Darkrai', type1: 'Dark' },
        { name: 'Darmanitan', type1: 'Fire', type2: 'Psychic' },
        { name: 'Darmanitan', type1: 'Fire' },
        { name: 'Darumaka', type1: 'Fire' },
        { name: 'Dedenne', type1: 'Electric', type2: 'Fairy' },
        { name: 'Deerling', type1: 'Normal', type2: 'Grass' },
        { name: 'Deino', type1: 'Dark', type2: 'Dragon' },
        { name: 'Delcatty', type1: 'Normal' },
        { name: 'Delibird', type1: 'Ice', type2: 'Flying' },
        { name: 'Delphox', type1: 'Fire', type2: 'Psychic' },
        { name: 'Deoxys', type1: 'Psychic' },
        { name: 'Deoxys', type1: 'Psychic' },
        { name: 'Deoxys', type1: 'Psychic' },
        { name: 'Deoxys', type1: 'Psychic' },
        { name: 'Dewgong', type1: 'Water', type2: 'Ice' },
        { name: 'Dewott', type1: 'Water' },
        { name: 'Dialga', type1: 'Steel', type2: 'Dragon' },
        { name: 'Diancie', type1: 'Rock', type2: 'Fairy' },
        { name: 'Diggersby', type1: 'Normal', type2: 'Ground' },
        { name: 'Diglett', type1: 'Ground' },
        { name: 'Ditto', type1: 'Normal' },
        { name: 'Dodrio', type1: 'Normal', type2: 'Flying' },
        { name: 'Doduo', type1: 'Normal', type2: 'Flying' },
        { name: 'Donphan', type1: 'Ground' },
        { name: 'Doublade', type1: 'Steel', type2: 'Ghost' },
        { name: 'Dragalge', type1: 'Poison', type2: 'Dragon' },
        { name: 'Dragonair', type1: 'Dragon' },
        { name: 'Dragonite', type1: 'Dragon', type2: 'Flying' },
        { name: 'Drapion', type1: 'Poison', type2: 'Dark' },
        { name: 'Dratini', type1: 'Dragon' },
        { name: 'Drifblim', type1: 'Ghost', type2: 'Flying' },
        { name: 'Drifloon', type1: 'Ghost', type2: 'Flying' },
        { name: 'Drilbur', type1: 'Ground' },
        { name: 'Drowzee', type1: 'Psychic' },
        { name: 'Druddigon', type1: 'Dragon' },
        { name: 'Ducklett', type1: 'Water', type2: 'Flying' },
        { name: 'Dugtrio', type1: 'Ground' },
        { name: 'Dunsparce', type1: 'Normal' },
        { name: 'Duosion', type1: 'Psychic' },
        { name: 'Durant', type1: 'Bug', type2: 'Steel' },
        { name: 'Dusclops', type1: 'Ghost' },
        { name: 'Dusknoir', type1: 'Ghost' },
        { name: 'Duskull', type1: 'Ghost' },
        { name: 'Dustox', type1: 'Bug', type2: 'Poison' },
        { name: 'Dwebble', type1: 'Bug', type2: 'Rock' },
        { name: 'Eelektrik', type1: 'Electric' },
        { name: 'Eelektross', type1: 'Electric' },
        { name: 'Eevee', type1: 'Normal' },
        { name: 'Ekans', type1: 'Poison' },
        { name: 'Electabuzz', type1: 'Electric' },
        { name: 'Electivire', type1: 'Electric' },
        { name: 'Electrike', type1: 'Electric' },
        { name: 'Electrode', type1: 'Electric' },
        { name: 'Elekid', type1: 'Electric' },
        { name: 'Elgyem', type1: 'Psychic' },
        { name: 'Emboar', type1: 'Fire', type2: 'Fighting' },
        { name: 'Emolga', type1: 'Electric', type2: 'Flying' },
        { name: 'Empoleon', type1: 'Water', type2: 'Steel' },
        { name: 'Entei', type1: 'Fire' },
        { name: 'Escavalier', type1: 'Bug', type2: 'Steel' },
        { name: 'Espeon', type1: 'Psychic' },
        { name: 'Espurr', type1: 'Psychic' },
        { name: 'Excadrill', type1: 'Ground', type2: 'Steel' },
        { name: 'Exeggcute', type1: 'Grass', type2: 'Psychic' },
        { name: 'Exeggutor', type1: 'Grass', type2: 'Psychic' },
        { name: 'Exploud', type1: 'Normal' },
        { name: 'Farfetch\'d', type1: 'Normal', type2: 'Flying' },
        { name: 'Fearow', type1: 'Normal', type2: 'Flying' },
        { name: 'Feebas', type1: 'Water' },
        { name: 'Fennekin', type1: 'Fire' },
        { name: 'Feraligatr', type1: 'Water' },
        { name: 'Ferroseed', type1: 'Grass', type2: 'Steel' },
        { name: 'Ferrothorn', type1: 'Grass', type2: 'Steel' },
        { name: 'Finneon', type1: 'Water' },
        { name: 'Flaaffy', type1: 'Electric' },
        { name: 'Flabébé', type1: 'Fairy' },
        { name: 'Flareon', type1: 'Fire' },
        { name: 'Fletchinder', type1: 'Fire', type2: 'Flying' },
        { name: 'Fletchling', type1: 'Normal', type2: 'Flying' },
        { name: 'Floatzel', type1: 'Water' },
        { name: 'Floette', type1: 'Fairy' },
        { name: 'Florges', type1: 'Fairy' },
        { name: 'Flygon', type1: 'Ground', type2: 'Dragon' },
        { name: 'Foongus', type1: 'Grass', type2: 'Poison' },
        { name: 'Forretress', type1: 'Bug', type2: 'Steel' },
        { name: 'Fraxure', type1: 'Dragon' },
        { name: 'Frillish', type1: 'Water', type2: 'Ghost' },
        { name: 'Frillish', type1: 'Water', type2: 'Ghost' },
        { name: 'Froakie', type1: 'Water' },
        { name: 'Frogadier', type1: 'Water' },
        { name: 'Froslass', type1: 'Ice', type2: 'Ghost' },
        { name: 'Furfrou', type1: 'Normal' },
        { name: 'Furret', type1: 'Normal' },
        { name: 'Gabite', type1: 'Dragon', type2: 'Ground' },
        { name: 'Gallade', type1: 'Psychic', type2: 'Fighting' },
        { name: 'Galvantula', type1: 'Bug', type2: 'Electric' },
        { name: 'Garbodor', type1: 'Poison' },
        { name: 'Garchomp', type1: 'Dragon', type2: 'Ground' },
        { name: 'Gardevoir', type1: 'Psychic', type2: 'Fairy' },
        { name: 'Gastly', type1: 'Ghost', type2: 'Poison' },
        { name: 'Gastrodon', type1: 'Water', type2: 'Ground' },
        { name: 'Gastrodon', type1: 'Water', type2: 'Ground' },
        { name: 'Genesect', type1: 'Bug', type2: 'Steel' },
        { name: 'Gengar', type1: 'Ghost', type2: 'Poison' },
        { name: 'Geodude', type1: 'Rock', type2: 'Ground' },
        { name: 'Gible', type1: 'Dragon', type2: 'Ground' },
        { name: 'Gigalith', type1: 'Rock' },
        { name: 'Girafarig', type1: 'Normal', type2: 'Psychic' },
        { name: 'Giratina', type1: 'Ghost', type2: 'Dragon' },
        { name: 'Giratina', type1: 'Ghost', type2: 'Dragon' },
        { name: 'Glaceon', type1: 'Ice' },
        { name: 'Glalie', type1: 'Ice' },
        { name: 'Glameow', type1: 'Normal' },
        { name: 'Gligar', type1: 'Ground', type2: 'Flying' },
        { name: 'Gliscor', type1: 'Ground', type2: 'Flying' },
        { name: 'Gloom', type1: 'Grass', type2: 'Poison' },
        { name: 'Gogoat', type1: 'Grass' },
        { name: 'Golbat', type1: 'Poison', type2: 'Flying' },
        { name: 'Goldeen', type1: 'Water' },
        { name: 'Golduck', type1: 'Water' },
        { name: 'Golem', type1: 'Rock', type2: 'Ground' },
        { name: 'Golett', type1: 'Ground', type2: 'Ghost' },
        { name: 'Golurk', type1: 'Ground', type2: 'Ghost' },
        { name: 'Goodra', type1: 'Dragon' },
        { name: 'Goomy', type1: 'Dragon' },
        { name: 'Gorebyss', type1: 'Water' },
        { name: 'Gothita', type1: 'Psychic' },
        { name: 'Gothitelle', type1: 'Psychic' },
        { name: 'Gothorita', type1: 'Psychic' },
        { name: 'Gourgeist', type1: 'Ghost', type2: 'Grass' },
        { name: 'Granbull', type1: 'Fairy' },
        { name: 'Graveler', type1: 'Rock', type2: 'Ground' },
        { name: 'Greninja', type1: 'Water', type2: 'Dark' },
        { name: 'Grimer', type1: 'Poison' },
        { name: 'Grotle', type1: 'Grass' },
        { name: 'Groudon', type1: 'Ground' },
        { name: 'Grovyle', type1: 'Grass' },
        { name: 'Growlithe', type1: 'Fire' },
        { name: 'Grumpig', type1: 'Psychic' },
        { name: 'Gulpin', type1: 'Poison' },
        { name: 'Gurdurr', type1: 'Fighting' },
        { name: 'Gyarados', type1: 'Water', type2: 'Flying' },
        { name: 'Happiny', type1: 'Normal' },
        { name: 'Hariyama', type1: 'Fighting' },
        { name: 'Haunter', type1: 'Ghost', type2: 'Poison' },
        { name: 'Hawlucha', type1: 'Fighting', type2: 'Flying' },
        { name: 'Haxorus', type1: 'Dragon' },
        { name: 'Heatmor', type1: 'Fire' },
        { name: 'Heatran', type1: 'Fire', type2: 'Steel' },
        { name: 'Heliolisk', type1: 'Electric', type2: 'Normal' },
        { name: 'Helioptile', type1: 'Electric', type2: 'Normal' },
        { name: 'Heracross', type1: 'Bug', type2: 'Fighting' },
        { name: 'Herdier', type1: 'Normal' },
        { name: 'Hippopotas', type1: 'Ground' },
        { name: 'Hippowdon', type1: 'Ground' },
        { name: 'Hitmonchan', type1: 'Fighting' },
        { name: 'Hitmonlee', type1: 'Fighting' },
        { name: 'Hitmontop', type1: 'Fighting' },
        { name: 'Ho-Oh', type1: 'Fire', type2: 'Flying' },
        { name: 'Honchkrow', type1: 'Dark', type2: 'Flying' },
        { name: 'Honedge', type1: 'Steel', type2: 'Ghost' },
        { name: 'Hoopa', type1: 'Psychic', type2: 'Dark' },
        { name: 'Hoopa', type1: 'Psychic', type2: 'Ghost' },
        { name: 'Hoothoot', type1: 'Normal', type2: 'Flying' },
        { name: 'Hoppip', type1: 'Grass', type2: 'Flying' },
        { name: 'Horsea', type1: 'Water' },
        { name: 'Houndoom', type1: 'Dark', type2: 'Fire' },
        { name: 'Houndour', type1: 'Dark', type2: 'Fire' },
        { name: 'Huntail', type1: 'Water' },
        { name: 'Hydreigon', type1: 'Dark', type2: 'Dragon' },
        { name: 'Hypno', type1: 'Psychic' },
        { name: 'Igglybuff', type1: 'Normal', type2: 'Fairy' },
        { name: 'Illumise', type1: 'Bug' },
        { name: 'Infernape', type1: 'Fire', type2: 'Fighting' },
        { name: 'Inkay', type1: 'Dark', type2: 'Psychic' },
        { name: 'Ivysaur', type1: 'Grass', type2: 'Poison' },
        { name: 'Jellicent', type1: 'Water', type2: 'Ghost' },
        { name: 'Jellicent', type1: 'Water', type2: 'Ghost' },
        { name: 'Jigglypuff', type1: 'Normal', type2: 'Fairy' },
        { name: 'Jirachi', type1: 'Steel', type2: 'Psychic' },
        { name: 'Jolteon', type1: 'Electric' },
        { name: 'Joltik', type1: 'Bug', type2: 'Electric' },
        { name: 'Jumpluff', type1: 'Grass', type2: 'Flying' },
        { name: 'Jynx', type1: 'Ice', type2: 'Psychic' },
        { name: 'Kabuto', type1: 'Rock', type2: 'Water' },
        { name: 'Kabutops', type1: 'Rock', type2: 'Water' },
        { name: 'Kadabra', type1: 'Psychic' },
        { name: 'Kakuna', type1: 'Bug', type2: 'Poison' },
        { name: 'Kangaskhan', type1: 'Normal' },
        { name: 'Karrablast', type1: 'Bug' },
        { name: 'Kecleon', type1: 'Normal' },
        { name: 'Keldeo', type1: 'Water', type2: 'Fighting' },
        { name: 'Kingdra', type1: 'Water', type2: 'Dragon' },
        { name: 'Kingler', type1: 'Water' },
        { name: 'Kirlia', type1: 'Psychic', type2: 'Fairy' },
        { name: 'Klang', type1: 'Steel' },
        { name: 'Klefki', type1: 'Steel', type2: 'Fairy' },
        { name: 'Klink', type1: 'Steel' },
        { name: 'Klinklang', type1: 'Steel' },
        { name: 'Koffing', type1: 'Poison' },
        { name: 'Krabby', type1: 'Water' },
        { name: 'Kricketot', type1: 'Bug' },
        { name: 'Kricketune', type1: 'Bug' },
        { name: 'Krokorok', type1: 'Ground', type2: 'Dark' },
        { name: 'Krookodile', type1: 'Ground', type2: 'Dark' },
        { name: 'Kyogre', type1: 'Water' },
        { name: 'Kyurem', type1: 'Dragon', type2: 'Ice' },
        { name: 'Lairon', type1: 'Steel', type2: 'Rock' },
        { name: 'Lampent', type1: 'Ghost', type2: 'Fire' },
        { name: 'Landorus', type1: 'Ground', type2: 'Flying' },
        { name: 'Lanturn', type1: 'Water', type2: 'Electric' },
        { name: 'Lapras', type1: 'Water', type2: 'Ice' },
        { name: 'Larvesta', type1: 'Bug', type2: 'Fire' },
        { name: 'Larvitar', type1: 'Rock', type2: 'Ground' },
        { name: 'Latias', type1: 'Dragon', type2: 'Psychic' },
        { name: 'Latios', type1: 'Dragon', type2: 'Psychic' },
        { name: 'Leafeon', type1: 'Grass' },
        { name: 'Leavanny', type1: 'Bug', type2: 'Grass' },
        { name: 'Ledian', type1: 'Bug', type2: 'Flying' },
        { name: 'Ledyba', type1: 'Bug', type2: 'Flying' },
        { name: 'Lickilicky', type1: 'Normal' },
        { name: 'Lickitung', type1: 'Normal' },
        { name: 'Liepard', type1: 'Dark' },
        { name: 'Lileep', type1: 'Rock', type2: 'Grass' },
        { name: 'Lilligant', type1: 'Grass' },
        { name: 'Lillipup', type1: 'Normal' },
        { name: 'Linoone', type1: 'Normal' },
        { name: 'Litleo', type1: 'Fire', type2: 'Normal' },
        { name: 'Litwick', type1: 'Ghost', type2: 'Fire' },
        { name: 'Lombre', type1: 'Water', type2: 'Grass' },
        { name: 'Lopunny', type1: 'Normal' },
        { name: 'Lotad', type1: 'Water', type2: 'Grass' },
        { name: 'Loudred', type1: 'Normal' },
        { name: 'Lucario', type1: 'Fighting', type2: 'Steel' },
        { name: 'Ludicolo', type1: 'Water', type2: 'Grass' },
        { name: 'Lugia', type1: 'Psychic', type2: 'Flying' },
        { name: 'Lumineon', type1: 'Water' },
        { name: 'Lunatone', type1: 'Rock', type2: 'Psychic' },
        { name: 'Luvdisc', type1: 'Water' },
        { name: 'Luxio', type1: 'Electric' },
        { name: 'Luxray', type1: 'Electric' },
        { name: 'Machamp', type1: 'Fighting' },
        { name: 'Machoke', type1: 'Fighting' },
        { name: 'Machop', type1: 'Fighting' },
        { name: 'Magby', type1: 'Fire' },
        { name: 'Magcargo', type1: 'Fire', type2: 'Rock' },
        { name: 'Magikarp', type1: 'Water' },
        { name: 'Magmar', type1: 'Fire' },
        { name: 'Magmortar', type1: 'Fire' },
        { name: 'Magnemite', type1: 'Electric', type2: 'Steel' },
        { name: 'Magneton', type1: 'Electric', type2: 'Steel' },
        { name: 'Magnezone', type1: 'Electric', type2: 'Steel' },
        { name: 'Makuhita', type1: 'Fighting' },
        { name: 'Malamar', type1: 'Dark', type2: 'Psychic' },
        { name: 'Mamoswine', type1: 'Ice', type2: 'Ground' },
        { name: 'Manaphy', type1: 'Water' },
        { name: 'Mandibuzz', type1: 'Dark', type2: 'Flying' },
        { name: 'Manectric', type1: 'Electric' },
        { name: 'Mankey', type1: 'Fighting' },
        { name: 'Mantine', type1: 'Water', type2: 'Flying' },
        { name: 'Mantyke', type1: 'Water', type2: 'Flying' },
        { name: 'Maractus', type1: 'Grass' },
        { name: 'Mareep', type1: 'Electric' },
        { name: 'Marill', type1: 'Water', type2: 'Fairy' },
        { name: 'Marowak', type1: 'Ground' },
        { name: 'Marshtomp', type1: 'Water', type2: 'Ground' },
        { name: 'Masquerain', type1: 'Bug', type2: 'Flying' },
        { name: 'Mawile', type1: 'Steel', type2: 'Fairy' },
        { name: 'Medicham', type1: 'Fighting', type2: 'Psychic' },
        { name: 'Meditite', type1: 'Fighting', type2: 'Psychic' },
        { name: 'Meganium', type1: 'Grass' },
        { name: 'Meloetta', type1: 'Normal', type2: 'Fighting' },
        { name: 'Meloetta', type1: 'Normal', type2: 'Psychic' },
        { name: 'Meowstic', type1: 'Psychic' },
        { name: 'Meowth', type1: 'Normal' },
        { name: 'Mesprit', type1: 'Psychic' },
        { name: 'Metagross', type1: 'Steel', type2: 'Psychic' },
        { name: 'Metang', type1: 'Steel', type2: 'Psychic' },
        { name: 'Metapod', type1: 'Bug' },
        { name: 'Mew', type1: 'Psychic' },
        { name: 'Mewtwo', type1: 'Psychic' },
        { name: 'Mienfoo', type1: 'Fighting' },
        { name: 'Mienshao', type1: 'Fighting' },
        { name: 'Mightyena', type1: 'Dark' },
        { name: 'Milotic', type1: 'Water' },
        { name: 'Miltank', type1: 'Normal' },
        { name: 'Mime Jr.', type1: 'Psychic', type2: 'Fairy' },
        { name: 'Minccino', type1: 'Normal' },
        { name: 'Minun', type1: 'Electric' },
        { name: 'Misdreavus', type1: 'Ghost' },
        { name: 'Mismagius', type1: 'Ghost' },
        { name: 'Moltres', type1: 'Fire', type2: 'Flying' },
        { name: 'Monferno', type1: 'Fire', type2: 'Fighting' },
        { name: 'Mothim', type1: 'Bug', type2: 'Flying' },
        { name: 'Mr. Mime', type1: 'Psychic', type2: 'Fairy' },
        { name: 'Mudkip', type1: 'Water' },
        { name: 'Muk', type1: 'Poison' },
        { name: 'Munchlax', type1: 'Normal' },
        { name: 'Munna', type1: 'Psychic' },
        { name: 'Murkrow', type1: 'Dark', type2: 'Flying' },
        { name: 'Musharna', type1: 'Psychic' },
        { name: 'Natu', type1: 'Psychic', type2: 'Flying' },
        { name: 'Nidoking', type1: 'Poison', type2: 'Ground' },
        { name: 'Nidoqueen', type1: 'Poison', type2: 'Ground' },
        { name: 'Nidoran♀', type1: 'Poison' },
        { name: 'Nidoran♂', type1: 'Poison' },
        { name: 'Nidorina', type1: 'Poison' },
        { name: 'Nidorino', type1: 'Poison' },
        { name: 'Nincada', type1: 'Bug', type2: 'Ground' },
        { name: 'Ninetales', type1: 'Fire' },
        { name: 'Ninjask', type1: 'Bug', type2: 'Flying' },
        { name: 'Noctowl', type1: 'Normal', type2: 'Flying' },
        { name: 'Noibat', type1: 'Flying', type2: 'Dragon' },
        { name: 'Noivern', type1: 'Flying', type2: 'Dragon' },
        { name: 'Nosepass', type1: 'Rock' },
        { name: 'Numel', type1: 'Fire', type2: 'Ground' },
        { name: 'Nuzleaf', type1: 'Grass', type2: 'Dark' },
        { name: 'Octillery', type1: 'Water' },
        { name: 'Oddish', type1: 'Grass', type2: 'Poison' },
        { name: 'Omanyte', type1: 'Rock', type2: 'Water' },
        { name: 'Omastar', type1: 'Rock', type2: 'Water' },
        { name: 'Onix', type1: 'Rock', type2: 'Ground' },
        { name: 'Oshawott', type1: 'Water' },
        { name: 'Pachirisu', type1: 'Electric' },
        { name: 'Palkia', type1: 'Water', type2: 'Dragon' },
        { name: 'Palpitoad', type1: 'Water', type2: 'Ground' },
        { name: 'Pancham', type1: 'Fighting' },
        { name: 'Pangoro', type1: 'Fighting', type2: 'Dark' },
        { name: 'Panpour', type1: 'Water' },
        { name: 'Pansage', type1: 'Grass' },
        { name: 'Pansear', type1: 'Fire' },
        { name: 'Paras', type1: 'Bug', type2: 'Grass' },
        { name: 'Parasect', type1: 'Bug', type2: 'Grass' },
        { name: 'Patrat', type1: 'Normal' },
        { name: 'Pawniard', type1: 'Dark', type2: 'Steel' },
        { name: 'Pelipper', type1: 'Water', type2: 'Flying' },
        { name: 'Persian', type1: 'Normal' },
        { name: 'Petilil', type1: 'Grass' },
        { name: 'Phanpy', type1: 'Ground' },
        { name: 'Phantump', type1: 'Ghost', type2: 'Grass' },
        { name: 'Phione', type1: 'Water' },
        { name: 'Pichu', type1: 'Electric' },
        { name: 'Pidgeot', type1: 'Normal', type2: 'Flying' },
        { name: 'Pidgeotto', type1: 'Normal', type2: 'Flying' },
        { name: 'Pidgey', type1: 'Normal', type2: 'Flying' },
        { name: 'Pidove', type1: 'Normal', type2: 'Flying' },
        { name: 'Pignite', type1: 'Fire', type2: 'Fighting' },
        { name: 'Pikachu', type1: 'Electric' },
        { name: 'Piloswine', type1: 'Ice', type2: 'Ground' },
        { name: 'Pineco', type1: 'Bug' },
        { name: 'Pinsir', type1: 'Bug' },
        { name: 'Piplup', type1: 'Water' },
        { name: 'Plusle', type1: 'Electric' },
        { name: 'Politoed', type1: 'Water' },
        { name: 'Poliwag', type1: 'Water' },
        { name: 'Poliwhirl', type1: 'Water' },
        { name: 'Poliwrath', type1: 'Water', type2: 'Fighting' },
        { name: 'Ponyta', type1: 'Fire' },
        { name: 'Poochyena', type1: 'Dark' },
        { name: 'Porygon', type1: 'Normal' },
        { name: 'Porygon-Z', type1: 'Normal' },
        { name: 'Porygon2', type1: 'Normal' },
        { name: 'Primeape', type1: 'Fighting' },
        { name: 'Prinplup', type1: 'Water' },
        { name: 'Probopass', type1: 'Rock', type2: 'Steel' },
        { name: 'Psyduck', type1: 'Water' },
        { name: 'Pumpkaboo', type1: 'Ghost', type2: 'Grass' },
        { name: 'Pupitar', type1: 'Rock', type2: 'Ground' },
        { name: 'Purrloin', type1: 'Dark' },
        { name: 'Purugly', type1: 'Normal' },
        { name: 'Pyroar', type1: 'Fire', type2: 'Normal' },
        { name: 'Quagsire', type1: 'Water', type2: 'Ground' },
        { name: 'Quilava', type1: 'Fire' },
        { name: 'Quilladin', type1: 'Grass' },
        { name: 'Qwilfish', type1: 'Water', type2: 'Poison' },
        { name: 'Raichu', type1: 'Electric' },
        { name: 'Raikou', type1: 'Electric' },
        { name: 'Ralts', type1: 'Psychic', type2: 'Fairy' },
        { name: 'Rampardos', type1: 'Rock' },
        { name: 'Rapidash', type1: 'Fire' },
        { name: 'Raticate', type1: 'Normal' },
        { name: 'Rattata', type1: 'Normal' },
        { name: 'Rayquaza', type1: 'Dragon', type2: 'Flying' },
        { name: 'Regice', type1: 'Ice' },
        { name: 'Regigigas', type1: 'Normal' },
        { name: 'Regirock', type1: 'Rock' },
        { name: 'Registeel', type1: 'Steel' },
        { name: 'Relicanth', type1: 'Water', type2: 'Rock' },
        { name: 'Remoraid', type1: 'Water' },
        { name: 'Reshiram', type1: 'Dragon', type2: 'Fire' },
        { name: 'Reuniclus', type1: 'Psychic' },
        { name: 'Rhydon', type1: 'Ground', type2: 'Rock' },
        { name: 'Rhyhorn', type1: 'Ground', type2: 'Rock' },
        { name: 'Rhyperior', type1: 'Ground', type2: 'Rock' },
        { name: 'Riolu', type1: 'Fighting' },
        { name: 'Roggenrola', type1: 'Rock' },
        { name: 'Roselia', type1: 'Grass', type2: 'Poison' },
        { name: 'Roserade', type1: 'Grass', type2: 'Poison' },
        { name: 'Rotom', type1: 'Electric', type2: 'Flying' },
        { name: 'Rotom', type1: 'Electric', type2: 'Ice' },
        { name: 'Rotom', type1: 'Electric', type2: 'Grass' },
        { name: 'Rotom', type1: 'Electric', type2: 'Ghost' },
        { name: 'Rotom', type1: 'Electric', type2: 'Fire' },
        { name: 'Rotom', type1: 'Electric', type2: 'Water' },
        { name: 'Rufflet', type1: 'Normal', type2: 'Flying' },
        { name: 'Sableye', type1: 'Dark', type2: 'Ghost' },
        { name: 'Salamence', type1: 'Dragon', type2: 'Flying' },
        { name: 'Samurott', type1: 'Water' },
        { name: 'Sandile', type1: 'Ground', type2: 'Dark' },
        { name: 'Sandshrew', type1: 'Ground' },
        { name: 'Sandslash', type1: 'Ground' },
        { name: 'Sawk', type1: 'Fighting' },
        { name: 'Sawsbuck', type1: 'Normal', type2: 'Grass' },
        { name: 'Scatterbug', type1: 'Bug' },
        { name: 'Sceptile', type1: 'Grass' },
        { name: 'Scizor', type1: 'Bug', type2: 'Steel' },
        { name: 'Scolipede', type1: 'Bug', type2: 'Poison' },
        { name: 'Scrafty', type1: 'Dark', type2: 'Fighting' },
        { name: 'Scraggy', type1: 'Dark', type2: 'Fighting' },
        { name: 'Scyther', type1: 'Bug', type2: 'Flying' },
        { name: 'Seadra', type1: 'Water' },
        { name: 'Seaking', type1: 'Water' },
        { name: 'Sealeo', type1: 'Ice', type2: 'Water' },
        { name: 'Seedot', type1: 'Grass' },
        { name: 'Seel', type1: 'Water' },
        { name: 'Seismitoad', type1: 'Water', type2: 'Ground' },
        { name: 'Sentret', type1: 'Normal' },
        { name: 'Serperior', type1: 'Grass' },
        { name: 'Servine', type1: 'Grass' },
        { name: 'Seviper', type1: 'Poison' },
        { name: 'Sewaddle', type1: 'Bug', type2: 'Grass' },
        { name: 'Sharpedo', type1: 'Water', type2: 'Dark' },
        { name: 'Shaymin', type1: 'Grass', type2: 'Flying' },
        { name: 'Shaymin', type1: 'Grass' },
        { name: 'Shedinja', type1: 'Bug', type2: 'Ghost' },
        { name: 'Shelgon', type1: 'Dragon' },
        { name: 'Shellder', type1: 'Water' },
        { name: 'Shellos', type1: 'Water' },
        { name: 'Shellos', type1: 'Water' },
        { name: 'Shelmet', type1: 'Bug' },
        { name: 'Shieldon', type1: 'Rock', type2: 'Steel' },
        { name: 'Shiftry', type1: 'Grass', type2: 'Dark' },
        { name: 'Shinx', type1: 'Electric' },
        { name: 'Shroomish', type1: 'Grass' },
        { name: 'Shuckle', type1: 'Bug', type2: 'Rock' },
        { name: 'Shuppet', type1: 'Ghost' },
        { name: 'Sigilyph', type1: 'Psychic', type2: 'Flying' },
        { name: 'Silcoon', type1: 'Bug' },
        { name: 'Simipour', type1: 'Water' },
        { name: 'Simisage', type1: 'Grass' },
        { name: 'Simisear', type1: 'Fire' },
        { name: 'Skarmory', type1: 'Steel', type2: 'Flying' },
        { name: 'Skiddo', type1: 'Grass' },
        { name: 'Skiploom', type1: 'Grass', type2: 'Flying' },
        { name: 'Skitty', type1: 'Normal' },
        { name: 'Skorupi', type1: 'Poison', type2: 'Bug' },
        { name: 'Skrelp', type1: 'Poison', type2: 'Water' },
        { name: 'Skuntank', type1: 'Poison', type2: 'Dark' },
        { name: 'Slaking', type1: 'Normal' },
        { name: 'Slakoth', type1: 'Normal' },
        { name: 'Sliggoo', type1: 'Dragon' },
        { name: 'Slowbro', type1: 'Water', type2: 'Psychic' },
        { name: 'Slowking', type1: 'Water', type2: 'Psychic' },
        { name: 'Slowpoke', type1: 'Water', type2: 'Psychic' },
        { name: 'Slugma', type1: 'Fire' },
        { name: 'Slurpuff', type1: 'Fairy' },
        { name: 'Smeargle', type1: 'Normal' },
        { name: 'Smoochum', type1: 'Ice', type2: 'Psychic' },
        { name: 'Sneasel', type1: 'Dark', type2: 'Ice' },
        { name: 'Snivy', type1: 'Grass' },
        { name: 'Snorlax', type1: 'Normal' },
        { name: 'Snorunt', type1: 'Ice' },
        { name: 'Snover', type1: 'Grass', type2: 'Ice' },
        { name: 'Snubbull', type1: 'Fairy' },
        { name: 'Solosis', type1: 'Psychic' },
        { name: 'Solrock', type1: 'Rock', type2: 'Psychic' },
        { name: 'Spearow', type1: 'Normal', type2: 'Flying' },
        { name: 'Spewpa', type1: 'Bug' },
        { name: 'Spheal', type1: 'Ice', type2: 'Water' },
        { name: 'Spinarak', type1: 'Bug', type2: 'Poison' },
        { name: 'Spinda', type1: 'Normal' },
        { name: 'Spiritomb', type1: 'Ghost', type2: 'Dark' },
        { name: 'Spoink', type1: 'Psychic' },
        { name: 'Spritzee', type1: 'Fairy' },
        { name: 'Squirtle', type1: 'Water' },
        { name: 'Stantler', type1: 'Normal' },
        { name: 'Staraptor', type1: 'Normal', type2: 'Flying' },
        { name: 'Staravia', type1: 'Normal', type2: 'Flying' },
        { name: 'Starly', type1: 'Normal', type2: 'Flying' },
        { name: 'Starmie', type1: 'Water', type2: 'Psychic' },
        { name: 'Staryu', type1: 'Water' },
        { name: 'Steelix', type1: 'Steel', type2: 'Ground' },
        { name: 'Stoutland', type1: 'Normal' },
        { name: 'Stunfisk', type1: 'Ground', type2: 'Electric' },
        { name: 'Stunky', type1: 'Poison', type2: 'Dark' },
        { name: 'Sudowoodo', type1: 'Rock' },
        { name: 'Suicune', type1: 'Water' },
        { name: 'Sunflora', type1: 'Grass' },
        { name: 'Sunkern', type1: 'Grass' },
        { name: 'Surskit', type1: 'Bug', type2: 'Water' },
        { name: 'Swablu', type1: 'Normal', type2: 'Flying' },
        { name: 'Swadloon', type1: 'Bug', type2: 'Grass' },
        { name: 'Swalot', type1: 'Poison' },
        { name: 'Swampert', type1: 'Water', type2: 'Ground' },
        { name: 'Swanna', type1: 'Water', type2: 'Flying' },
        { name: 'Swellow', type1: 'Normal', type2: 'Flying' },
        { name: 'Swinub', type1: 'Ice', type2: 'Ground' },
        { name: 'Swirlix', type1: 'Fairy' },
        { name: 'Swoobat', type1: 'Psychic', type2: 'Flying' },
        { name: 'Sylveon', type1: 'Fairy' },
        { name: 'Taillow', type1: 'Normal', type2: 'Flying' },
        { name: 'Talonflame', type1: 'Fire', type2: 'Flying' },
        { name: 'Tangela', type1: 'Grass' },
        { name: 'Tangrowth', type1: 'Grass' },
        { name: 'Tauros', type1: 'Normal' },
        { name: 'Teddiursa', type1: 'Normal' },
        { name: 'Tentacool', type1: 'Water', type2: 'Poison' },
        { name: 'Tentacruel', type1: 'Water', type2: 'Poison' },
        { name: 'Tepig', type1: 'Fire' },
        { name: 'Terrakion', type1: 'Rock', type2: 'Fighting' },
        { name: 'Throh', type1: 'Fighting' },
        { name: 'Thundurus', type1: 'Electric', type2: 'Flying' },
        { name: 'Timburr', type1: 'Fighting' },
        { name: 'Tirtouga', type1: 'Water', type2: 'Rock' },
        { name: 'Togekiss', type1: 'Fairy', type2: 'Flying' },
        { name: 'Togepi', type1: 'Fairy' },
        { name: 'Togetic', type1: 'Fairy', type2: 'Flying' },
        { name: 'Torchic', type1: 'Fire' },
        { name: 'Torkoal', type1: 'Fire' },
        { name: 'Tornadus', type1: 'Flying' },
        { name: 'Torterra', type1: 'Grass', type2: 'Ground' },
        { name: 'Totodile', type1: 'Water' },
        { name: 'Toxicroak', type1: 'Poison', type2: 'Fighting' },
        { name: 'Tranquill', type1: 'Normal', type2: 'Flying' },
        { name: 'Trapinch', type1: 'Ground' },
        { name: 'Treecko', type1: 'Grass' },
        { name: 'Trevenant', type1: 'Ghost', type2: 'Grass' },
        { name: 'Tropius', type1: 'Grass', type2: 'Flying' },
        { name: 'Trubbish', type1: 'Poison' },
        { name: 'Turtwig', type1: 'Grass' },
        { name: 'Tympole', type1: 'Water' },
        { name: 'Tynamo', type1: 'Electric' },
        { name: 'Typhlosion', type1: 'Fire' },
        { name: 'Tyranitar', type1: 'Rock', type2: 'Dark' },
        { name: 'Tyrantrum', type1: 'Rock', type2: 'Dragon' },
        { name: 'Tyrogue', type1: 'Fighting' },
        { name: 'Tyrunt', type1: 'Rock', type2: 'Dragon' },
        { name: 'Umbreon', type1: 'Dark' },
        { name: 'Unfezant', type1: 'Normal', type2: 'Flying' },
        { name: 'Unfezant', type1: 'Normal', type2: 'Flying' },
        { name: 'Unown', type1: 'Psychic' },
        { name: 'Ursaring', type1: 'Normal' },
        { name: 'Uxie', type1: 'Psychic' },
        { name: 'Vanillish', type1: 'Ice' },
        { name: 'Vanillite', type1: 'Ice' },
        { name: 'Vanilluxe', type1: 'Ice' },
        { name: 'Vaporeon', type1: 'Water' },
        { name: 'Venipede', type1: 'Bug', type2: 'Poison' },
        { name: 'Venomoth', type1: 'Bug', type2: 'Poison' },
        { name: 'Venonat', type1: 'Bug', type2: 'Poison' },
        { name: 'Venusaur', type1: 'Grass', type2: 'Poison' },
        { name: 'Vespiquen', type1: 'Bug', type2: 'Flying' },
        { name: 'Vibrava', type1: 'Ground', type2: 'Dragon' },
        { name: 'Victini', type1: 'Psychic', type2: 'Fire' },
        { name: 'Victreebel', type1: 'Grass', type2: 'Poison' },
        { name: 'Vigoroth', type1: 'Normal' },
        { name: 'Vileplume', type1: 'Grass', type2: 'Poison' },
        { name: 'Virizion', type1: 'Grass', type2: 'Fighting' },
        { name: 'Vivillon', type1: 'Bug', type2: 'Flying' },
        { name: 'Volbeat', type1: 'Bug' },
        { name: 'Volcanion', type1: 'Fire', type2: 'Water' },
        { name: 'Volcarona', type1: 'Bug', type2: 'Fire' },
        { name: 'Voltorb', type1: 'Electric' },
        { name: 'Vullaby', type1: 'Dark', type2: 'Flying' },
        { name: 'Vulpix', type1: 'Fire' },
        { name: 'Wailmer', type1: 'Water' },
        { name: 'Wailord', type1: 'Water' },
        { name: 'Walrein', type1: 'Ice', type2: 'Water' },
        { name: 'Wartortle', type1: 'Water' },
        { name: 'Watchog', type1: 'Normal' },
        { name: 'Weavile', type1: 'Dark', type2: 'Ice' },
        { name: 'Weedle', type1: 'Bug', type2: 'Poison' },
        { name: 'Weepinbell', type1: 'Grass', type2: 'Poison' },
        { name: 'Weezing', type1: 'Poison' },
        { name: 'Whimsicott', type1: 'Grass', type2: 'Fairy' },
        { name: 'Whirlipede', type1: 'Bug', type2: 'Poison' },
        { name: 'Whiscash', type1: 'Water', type2: 'Ground' },
        { name: 'Whismur', type1: 'Normal' },
        { name: 'Wigglytuff', type1: 'Normal', type2: 'Fairy' },
        { name: 'Wingull', type1: 'Water', type2: 'Flying' },
        { name: 'Wobbuffet', type1: 'Psychic' },
        { name: 'Woobat', type1: 'Psychic', type2: 'Flying' },
        { name: 'Wooper', type1: 'Water', type2: 'Ground' },
        { name: 'Wormadam', type1: 'Bug', type2: 'Ground' },
        { name: 'Wormadam', type1: 'Bug', type2: 'Steel' },
        { name: 'Wormadam', type1: 'Bug', type2: 'Grass' },
        { name: 'Wurmple', type1: 'Bug' },
        { name: 'Wynaut', type1: 'Psychic' },
        { name: 'Xatu', type1: 'Psychic', type2: 'Flying' },
        { name: 'Xerneas', type1: 'Fairy' },
        { name: 'Yamask', type1: 'Ghost' },
        { name: 'Yanma', type1: 'Bug', type2: 'Flying' },
        { name: 'Yanmega', type1: 'Bug', type2: 'Flying' },
        { name: 'Yveltal', type1: 'Dark', type2: 'Flying' },
        { name: 'Zangoose', type1: 'Normal' },
        { name: 'Zapdos', type1: 'Electric', type2: 'Flying' },
        { name: 'Zebstrika', type1: 'Electric' },
        { name: 'Zekrom', type1: 'Dragon', type2: 'Electric' },
        { name: 'Zigzagoon', type1: 'Normal' },
        { name: 'Zoroark', type1: 'Dark' },
        { name: 'Zorua', type1: 'Dark' },
        { name: 'Zubat', type1: 'Poison', type2: 'Flying' },
        { name: 'Zweilous', type1: 'Dark', type2: 'Dragon' },
        { name: 'Zygarde', type1: 'Dragon', type2: 'Ground' }]
      }},
      methods:{
        // show:function(pokemon)
        // {
        //   return (pokemon.name.toLowerCase().startsWith(this.search)||pokemon.name=="Pokemon")
        // }
        pokemonChanged:function(){
          // console.log("change in child");
          var childMessage=[this.childNumber,this.selected];
          this.$dispatch('pokemon_change', childMessage);
        }
      }
    }

    </script>

    <!-- Add "scoped" attribute to limit CSS to this component only -->
    <style scoped>
    </style>
