import Vue from 'vue'
import App from './App'
import Hello from './components/Hello'
import pokemonoptions from './components/pokemonoptions'

/* eslint-disable no-new */
new Vue({
  el: 'body',
  components: { App,pokemonoptions,Hello },
  data:{
    pokemon:[{name:'Pokemon'},{name:'Pokemon'},{name:'Pokemon'},{name:'Pokemon'},{name:'Pokemon'},{name:'Pokemon'}],
    types:["Normal","Fighting","Flying","Poison","Ground","Rock","Bug",
    "Ghost","Steel","Fire",	"Water","Grass","Electric","Psychic","Ice","Dragon","Dark",	"Fairy"],
    typeEffectiveness:{ 'Normal': { 'Normal': 1,
    'Fighting': 1,
    'Flying': 1,
    'Poison': 1,
    'Ground': 1,
    'Rock': 0.5,
    'Bug': 1,
    'Ghost': 0,
    'Steel': 0.5,
    'Fire': 1,
    'Water': 1,
    'Grass': 1,
    'Electric': 1,
    'Psychic': 1,
    'Ice': 1,
    'Dragon': 1,
    'Dark': 1,
    'Fairy': 1 },
    'Fighting': { 'Normal': 2,
    'Fighting': 1,
    'Flying': 0.5,
    'Poison': 0.5,
    'Ground': 1,
    'Rock': 2,
    'Bug': 0.5,
    'Ghost': 0,
    'Steel': 2,
    'Fire': 1,
    'Water': 1,
    'Grass': 1,
    'Electric': 1,
    'Psychic': 0.5,
    'Ice': 2,
    'Dragon': 1,
    'Dark': 2,
    'Fairy': 0.5 },
    'Flying': { 'Normal': 1,
    'Fighting': 2,
    'Flying': 1,
    'Poison': 1,
    'Ground': 1,
    'Rock': 0.5,
    'Bug': 2,
    'Ghost': 1,
    'Steel': 0.5,
    'Fire': 1,
    'Water': 1,
    'Grass': 2,
    'Electric': 0.5,
    'Psychic': 1,
    'Ice': 1,
    'Dragon': 1,
    'Dark': 1,
    'Fairy': 1 },
    'Poison': { 'Normal': 1,
    'Fighting': 1,
    'Flying': 1,
    'Poison': 0.5,
    'Ground': 0.5,
    'Rock': 0.5,
    'Bug': 1,
    'Ghost': 0.5,
    'Steel': 0,
    'Fire': 1,
    'Water': 1,
    'Grass': 2,
    'Electric': 1,
    'Psychic': 1,
    'Ice': 1,
    'Dragon': 1,
    'Dark': 1,
    'Fairy': 2 },
    'Ground': { 'Normal': 1,
    'Fighting': 1,
    'Flying': 0,
    'Poison': 2,
    'Ground': 1,
    'Rock': 2,
    'Bug': 0.5,
    'Ghost': 1,
    'Steel': 2,
    'Fire': 2,
    'Water': 1,
    'Grass': 0.5,
    'Electric': 2,
    'Psychic': 1,
    'Ice': 1,
    'Dragon': 1,
    'Dark': 1,
    'Fairy': 1 },
    'Rock': { 'Normal': 1,
    'Fighting': 0.5,
    'Flying': 2,
    'Poison': 1,
    'Ground': 0.5,
    'Rock': 1,
    'Bug': 2,
    'Ghost': 1,
    'Steel': 0.5,
    'Fire': 2,
    'Water': 1,
    'Grass': 1,
    'Electric': 1,
    'Psychic': 1,
    'Ice': 2,
    'Dragon': 1,
    'Dark': 1,
    'Fairy': 1 },
    'Bug': { 'Normal': 1,
    'Fighting': 0.5,
    'Flying': 0.5,
    'Poison': 0.5,
    'Ground': 1,
    'Rock': 1,
    'Bug': 1,
    'Ghost': 0.5,
    'Steel': 0.5,
    'Fire': 0.5,
    'Water': 1,
    'Grass': 2,
    'Electric': 1,
    'Psychic': 2,
    'Ice': 1,
    'Dragon': 1,
    'Dark': 2,
    'Fairy': 0.5 },
    'Ghost': { 'Normal': 0,
    'Fighting': 1,
    'Flying': 1,
    'Poison': 1,
    'Ground': 1,
    'Rock': 1,
    'Bug': 1,
    'Ghost': 2,
    'Steel': 1,
    'Fire': 1,
    'Water': 1,
    'Grass': 1,
    'Electric': 1,
    'Psychic': 2,
    'Ice': 1,
    'Dragon': 1,
    'Dark': 0.5,
    'Fairy': 1 },
    'Steel': { 'Normal': 1,
    'Fighting': 1,
    'Flying': 1,
    'Poison': 1,
    'Ground': 1,
    'Rock': 2,
    'Bug': 1,
    'Ghost': 1,
    'Steel': 0.5,
    'Fire': 0.5,
    'Water': 0.5,
    'Grass': 1,
    'Electric': 0.5,
    'Psychic': 1,
    'Ice': 2,
    'Dragon': 1,
    'Dark': 1,
    'Fairy': 2 },
    'Fire': { 'Normal': 1,
    'Fighting': 1,
    'Flying': 1,
    'Poison': 1,
    'Ground': 1,
    'Rock': 0.5,
    'Bug': 2,
    'Ghost': 1,
    'Steel': 2,
    'Fire': 0.5,
    'Water': 0.5,
    'Grass': 2,
    'Electric': 1,
    'Psychic': 1,
    'Ice': 2,
    'Dragon': 0.5,
    'Dark': 1,
    'Fairy': 1 },
    'Water': { 'Normal': 1,
    'Fighting': 1,
    'Flying': 1,
    'Poison': 1,
    'Ground': 2,
    'Rock': 2,
    'Bug': 1,
    'Ghost': 1,
    'Steel': 1,
    'Fire': 2,
    'Water': 0.5,
    'Grass': 0.5,
    'Electric': 1,
    'Psychic': 1,
    'Ice': 1,
    'Dragon': 0.5,
    'Dark': 1,
    'Fairy': 1 },
    'Grass': { 'Normal': 1,
    'Fighting': 1,
    'Flying': 0.5,
    'Poison': 0.5,
    'Ground': 2,
    'Rock': 2,
    'Bug': 0.5,
    'Ghost': 1,
    'Steel': 0.5,
    'Fire': 0.5,
    'Water': 2,
    'Grass': 0.5,
    'Electric': 1,
    'Psychic': 1,
    'Ice': 1,
    'Dragon': 0.5,
    'Dark': 1,
    'Fairy': 1 },
    'Electric': { 'Normal': 1,
    'Fighting': 1,
    'Flying': 2,
    'Poison': 1,
    'Ground': 0,
    'Rock': 1,
    'Bug': 1,
    'Ghost': 1,
    'Steel': 1,
    'Fire': 1,
    'Water': 2,
    'Grass': 0.5,
    'Electric': 0.5,
    'Psychic': 1,
    'Ice': 1,
    'Dragon': 0.5,
    'Dark': 1,
    'Fairy': 1 },
    'Psychic': { 'Normal': 1,
    'Fighting': 2,
    'Flying': 1,
    'Poison': 2,
    'Ground': 1,
    'Rock': 1,
    'Bug': 1,
    'Ghost': 1,
    'Steel': 0.5,
    'Fire': 1,
    'Water': 1,
    'Grass': 1,
    'Electric': 1,
    'Psychic': 0.5,
    'Ice': 1,
    'Dragon': 1,
    'Dark': 0,
    'Fairy': 1 },
    'Ice': { 'Normal': 1,
    'Fighting': 1,
    'Flying': 2,
    'Poison': 1,
    'Ground': 2,
    'Rock': 1,
    'Bug': 1,
    'Ghost': 1,
    'Steel': 0.5,
    'Fire': 0.5,
    'Water': 0.5,
    'Grass': 2,
    'Electric': 1,
    'Psychic': 1,
    'Ice': 0.5,
    'Dragon': 2,
    'Dark': 1,
    'Fairy': 1 },
    'Dragon': { 'Normal': 1,
    'Fighting': 1,
    'Flying': 1,
    'Poison': 1,
    'Ground': 1,
    'Rock': 1,
    'Bug': 1,
    'Ghost': 1,
    'Steel': 0.5,
    'Fire': 1,
    'Water': 1,
    'Grass': 1,
    'Electric': 1,
    'Psychic': 1,
    'Ice': 1,
    'Dragon': 2,
    'Dark': 1,
    'Fairy': 0 },
    'Dark': { 'Normal': 1,
    'Fighting': 0.5,
    'Flying': 1,
    'Poison': 1,
    'Ground': 1,
    'Rock': 1,
    'Bug': 1,
    'Ghost': 2,
    'Steel': 1,
    'Fire': 1,
    'Water': 1,
    'Grass': 1,
    'Electric': 1,
    'Psychic': 2,
    'Ice': 1,
    'Dragon': 1,
    'Dark': 0.5,
    'Fairy': 0.5 },
    'Fairy': { 'Normal': 1,
    'Fighting': 2,
    'Flying': 1,
    'Poison': 0.5,
    'Ground': 1,
    'Rock': 1,
    'Bug': 1,
    'Ghost': 1,
    'Steel': 0.5,
    'Fire': 0.5,
    'Water': 1,
    'Grass': 1,
    'Electric': 1,
    'Psychic': 1,
    'Ice': 1,
    'Dragon': 2,
    'Dark': 2,
    'Fairy': 1 } }
    ,
    count: {
      'Normal': {
        'immunity': 0,
        'double_resistance': 0,
        'resistance': 0,
        'normal': 0,
        'weakness': 0,
        'double_weakness': 0
      },
      'Fighting': {
        'immunity': 0,
        'double_resistance': 0,
        'resistance': 0,
        'normal': 0,
        'weakness': 0,
        'double_weakness': 0
      },
      'Flying': {
        'immunity': 0,
        'double_resistance': 0,
        'resistance': 0,
        'normal': 0,
        'weakness': 0,
        'double_weakness': 0
      },
      'Poison': {
        'immunity': 0,
        'double_resistance': 0,
        'resistance': 0,
        'normal': 0,
        'weakness': 0,
        'double_weakness': 0
      },
      'Ground': {
        'immunity': 0,
        'double_resistance': 0,
        'resistance': 0,
        'normal': 0,
        'weakness': 0,
        'double_weakness': 0
      },
      'Rock': {
        'immunity': 0,
        'double_resistance': 0,
        'resistance': 0,
        'normal': 0,
        'weakness': 0,
        'double_weakness': 0
      },
      'Bug': {
        'immunity': 0,
        'double_resistance': 0,
        'resistance': 0,
        'normal': 0,
        'weakness': 0,
        'double_weakness': 0
      },
      'Ghost': {
        'immunity': 0,
        'double_resistance': 0,
        'resistance': 0,
        'normal': 0,
        'weakness': 0,
        'double_weakness': 0
      },
      'Steel': {
        'immunity': 0,
        'double_resistance': 0,
        'resistance': 0,
        'normal': 0,
        'weakness': 0,
        'double_weakness': 0
      },
      'Fire': {
        'immunity': 0,
        'double_resistance': 0,
        'resistance': 0,
        'normal': 0,
        'weakness': 0,
        'double_weakness': 0
      },
      'Water': {
        'immunity': 0,
        'double_resistance': 0,
        'resistance': 0,
        'normal': 0,
        'weakness': 0,
        'double_weakness': 0
      },
      'Grass': {
        'immunity': 0,
        'double_resistance': 0,
        'resistance': 0,
        'normal': 0,
        'weakness': 0,
        'double_weakness': 0
      },
      'Electric': {
        'immunity': 0,
        'double_resistance': 0,
        'resistance': 0,
        'normal': 0,
        'weakness': 0,
        'double_weakness': 0
      },
      'Psychic': {
        'immunity': 0,
        'double_resistance': 0,
        'resistance': 0,
        'normal': 0,
        'weakness': 0,
        'double_weakness': 0
      },
      'Ice': {
        'immunity': 0,
        'double_resistance': 0,
        'resistance': 0,
        'normal': 0,
        'weakness': 0,
        'double_weakness': 0
      },
      'Dragon': {
        'immunity': 0,
        'double_resistance': 0,
        'resistance': 0,
        'normal': 0,
        'weakness': 0,
        'double_weakness': 0
      },
      'Dark': {
        'immunity': 0,
        'double_resistance': 0,
        'resistance': 0,
        'normal': 0,
        'weakness': 0,
        'double_weakness': 0
      },
      'Fairy': {
        'immunity': 0,
        'double_resistance': 0,
        'resistance': 0,
        'normal': 0,
        'weakness': 0,
        'double_weakness': 0
      }
    }
    ,modifiers:['immunity','double_resistance','resistance','normal','weakness','double_weakness']
  },
  methods:
  {
    resetCount:function()
    {
      for(var type of this.types)
      {
        for(var modifier of this.modifiers)
        {
          this.count[type][modifier]=0;
        }
      }
    },
    typeDamageToPokemon:function(type,pokemon)
    {
      var damage=1;
      damage= damage* this.typeEffectiveness[type][pokemon.type1];
      if(pokemon.hasOwnProperty("type2"))
      damage=damage*this.typeEffectiveness[type][pokemon.type2];
      return damage;

    },
    calculatePokemon:function(pokemon)
    {
      for(var i=0;i<this.types.length;i++)
      {
        var type=this.types[i];
        var temp=this.typeDamageToPokemon(type,pokemon);
        if(temp==0)this.count[type]['immunity']++;
        else if(temp==0.25)this.count[type]['double_resistance']++;
        else if(temp==0.5)this.count[type]['resistance']++;
        else if(temp==1)this.count[type]['normal']++;
        else if(temp==2)this.count[type]['weakness']++;
        else if(temp==4)this.count[type]['double_weakness']++;
      }
    },
    calculateTotal:function()
    {
      var poke;
      this.resetCount();
      for(var j=0;j<6;j++)
      {
        poke=this.pokemon[j];
        if(poke.name!="Pokemon")this.calculatePokemon(poke);
      }
    }
  },
  events: {
    'pokemon_change': function (msg) {
      var childNumber=msg[0]-1;
      var newPokemon=msg[1];
      this.pokemon[childNumber]=newPokemon;
      this.calculateTotal();
    }
  }})
